### ISSUE TITLE
Create ARGoS simulation prototype & interface

### ISSUE THREAD

**Issue by pepsiman3** [IEEE-Robotics-Club/MSU-NASA-Minds-2023#25]
We will need a working simulation of a swarm algorithm soon. This should ideally have some basic features such as

- [x] Low and high level motor driver functions
- [x] A pathfinding algorithm
- [x] Waypoint system
- [x] Virtual LIDAR sensor
- [ ] Basic fault detection & callbacks

These functions will be Lua-based but should ideally be structured in a way so that their function interface can be transitioned into C as painlessly as possible. This includes the use of tables as stand-ins for C structures, functions for initializers, etc

**Comment by pepsiman3** [comment]
for example, https://github.com/IEEE-Robotics-Club/MSU-NASA-Minds-2023/blob/c58acfaf0b95bf55d4a456c83b780e650a0dea42/ARGoS-Simulations/MSU%20Sims/movement-MVP/motor-functions.lua#L9-L32

could transitioned into similar C code,
`
void motor_init(motor_t *motor, uint8_t pin, uint16_t max_pwm);

void motor_drive(motor_t *motor, int16_t pwm);
`

**Comment by Fife** [comment]
Looks like the only thing remaining on this task list is the fault detection

**Comment by Fife** [comment]
Basic Fault Detection will be rolled into state machine issue
